{{- if .Values.opencostProductConfigs }}
{{- if .Values.opencostProductConfigs.createServiceKeySecret }}
{{- if .Values.opencostProductConfigs.awsServiceKeyName }}
apiVersion: v1
kind: Secret
metadata:
  name: cloud-service-key
  labels:
    {{ include "costmodel.commonLabels" . | nindent 4 }}
type: Opaque
stringData:
  service-key.json: |-
    {
      "aws_access_key_id": "{{ .Values.opencostProductConfigs.awsServiceKeyName }}",
      "aws_secret_access_key": "{{ .Values.opencostProductConfigs.awsServiceKeyPassword }}"
    }
{{- end -}}
{{- end -}}
{{- end -}}
