{{- if .Values.opencostProductConfigs }}
{{- if .Values.opencostProductConfigs.createServiceKeySecret }}
{{- if .Values.opencostProductConfigs.azureSubscriptionID }}
apiVersion: v1
kind: Secret
metadata:
  name: cloud-service-key
  labels:
    {{ include "costmodel.commonLabels" . | nindent 4 }}
type: Opaque
stringData:
  service-key.json: |-
    {
      "subscriptionId": "{{ .Values.opencostProductConfigs.azureSubscriptionID }}",
      "serviceKey": {
        "appId": "{{ .Values.opencostProductConfigs.azureClientID }}",
        "password": "{{ .Values.opencostProductConfigs.azureClientPassword }}",
        "tenant": "{{ .Values.opencostProductConfigs.azureTenantID }}"
      }
    }
{{- end -}}
{{- end -}}
{{- end -}}
