{{/*This method of configuration is deprecated*/}}
{{- if .Values.opencostProductConfigs }}
{{- if .Values.opencostProductConfigs.azureStorageCreateSecret }}
{{- if .Values.opencostProductConfigs.azureStorageAccessKey }}
{{- if .Values.opencostProductConfigs.azureStorageAccount }}
{{- if .Values.opencostProductConfigs.azureStorageContainer }}
apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-config
  labels:
    {{ include "costmodel.commonLabels" . | nindent 4 }}
type: Opaque
stringData:
  azure-storage-config.json: |-
    {
    	"azureStorageAccount": "{{ .Values.opencostProductConfigs.azureStorageAccount }}",
    	"azureStorageAccessKey": "{{ .Values.opencostProductConfigs.azureStorageAccessKey }}",
    	"azureStorageContainer": "{{ .Values.opencostProductConfigs.azureStorageContainer }}"
    }
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
