{{- if .Values.opencost.metrics.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-metrics-config
  namespace: {{ include "opencost.namespace" . }}
  labels: {{- include "opencost.labels" . | nindent 4 }}
data:
  metrics.json: |-
    {"disabledMetrics": {{ toJson .Values.opencost.metrics.config.disabledMetrics }} }
{{- end }}
