{{- if .Values.podSecurityPolicy }}
{{- if .Values.podSecurityPolicy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: {{ template "costmodel.fullname" . }}-psp
    labels:
      {{ include "costmodel.commonLabels" . | nindent 6 }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ template "costmodel.fullname" . }}-psp
subjects:
- kind: ServiceAccount
  name: {{ template "costmodel.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
