{{- if .Values.federatedETL.federator }}
{{- if .Values.federatedETL.federator.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "costmodel.fullname" . }}-federator
  labels:
    {{ include "costmodel.commonLabels" . | nindent 4 }}
data:
{{- $root := . }}
    federator.json: '{{ toJson .Values.federatedETL.federator }}'
{{- end -}}
{{- end -}}