{{- if .Values.serviceMonitor }}
{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "costmodel.fullname" . }}
  labels:
    {{ include "costmodel.commonLabels" . | nindent 4 }}
    {{- if .Values.serviceMonitor.additionalLabels }}
    {{ toYaml .Values.serviceMonitor.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: tcp-model
      honorLabels: true
      interval: 1m
      scrapeTimeout: 10s
      path: /metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{ include "costmodel.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
