{{- if .Values.global.notifications.alertConfigs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default "alert-configs" .Values.alertConfigmapName }}
  labels:
    {{ include "costmodel.commonLabels" . | nindent 4 }}
data:
  alerts.json: '{{ toJson .Values.global.notifications.alertConfigs }}'
{{- end -}}
