{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
{{- if .Values.podSecurityPolicy }}
{{- if .Values.podSecurityPolicy.enabled }}
apiVersion: {{ include "costmodel.podSecurityPolicy.apiVersion" . }}
kind: PodSecurityPolicy
metadata:
    name: {{ template "costmodel.fullname" . }}-psp
    labels:
      {{ include "costmodel.commonLabels" . | nindent 6 }}
spec:
    privileged: false
    seLinux:
        rule: RunAsAny
    supplementalGroups:
        rule: RunAsAny
    runAsUser:
        rule: RunAsAny
    fsGroup:
        rule: RunAsAny
    volumes:
        - '*'
{{- end }}
{{- end }}
{{- end }}
