{{- $serviceName := include "costmodel.serviceName" . -}}
{{- $nginxPort := .Values.service.targetPort | default 9090 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  labels:
    {{ include "costmodel.commonLabels" . | nindent 4 }}
data:
  nginx.conf: |
    gzip_static  on;

    # Enable gzip encoding for content of the provided types of 50kb and higher.
    gzip on;
    gzip_min_length 50000;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types
        application/atom+xml
        application/geo+json
        application/javascript
        application/x-javascript
        application/json
        application/ld+json
        application/manifest+json
        application/rdf+xml
        application/rss+xml
        application/vnd.ms-fontobject
        application/wasm
        application/x-web-app-manifest+json
        application/xhtml+xml
        application/xml
        font/eot
        font/otf
        font/ttf
        image/bmp
        image/svg+xml
        text/cache-manifest
        text/calendar
        text/css
        text/javascript
        text/markdown
        text/plain
        text/xml
        text/x-component
        text/x-cross-domain-policy;

    upstream model {
{{- if (((.Values.opencostFrontend).model).fqdn) }}
        server {{ .Values.opencostFrontend.model.fqdn }};
{{- else }}
        server {{ $serviceName }}.{{ .Release.Namespace }}:9003;
{{- end }}
    }

    server {
        server_name _;
        root /var/www;
        index index.html;
        large_client_header_buffers 4 32k;
        add_header Cache-Control "must-revalidate";

        error_page 504 /custom_504.html;
        location = /custom_504.html {
            internal;
        }

        add_header Cache-Control "max-age=300";
        location / {
            try_files $uri $uri/ /index.html;
        }

{{- if .Values.opencostFrontend.imageVersion }}
        add_header ETag "{{ $.Values.opencostFrontend.imageVersion }}";
{{- else }}
        add_header ETag "{{ $.Chart.Version }}";
{{- end }}
        listen {{ $nginxPort }};
        listen [::]:{{ $nginxPort }};
        location /healthz {
            return 200 'OK';
        }
        location /allocation {
            proxy_connect_timeout       180;
            proxy_send_timeout          180;
            proxy_read_timeout          180;
            proxy_pass http://model/;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
