{{- if and .Values.opencost.ui.enabled .Values.opencost.ui.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "opencost.fullname" . }}-ingress
  labels:
    {{- include "opencost.labels" . | nindent 4 }}
  {{- with .Values.opencost.ui.ingress.annotations }}
  annotations: {{ toYaml .Values.opencost.ui.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.opencost.ui.ingress.ingressClassName }}
  ingressClassName: {{ .Values.opencost.ui.ingress.ingressClassName }}
{{- end }}
{{- if .Values.opencost.ui.ingress.tls }}
  tls:
  {{- range .Values.opencost.ui.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.opencost.ui.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "opencost.fullname" $ }}
                port:
                  name: http-ui
        {{- end }}
  {{- end }}
{{- end }}
