{{- if and .Values.opencost.platforms.openshift.enabled .Values.opencost.platforms.openshift.createMonitoringResourceReaderRoleBinding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ include "opencost.namespace" . }}
  name: {{ include "opencost.fullname" . }}-reader
subjects:
- kind: ServiceAccount
  name: {{ .Values.opencost.platforms.openshift.monitoringServiceAccountName | quote }}
  namespace: {{ .Values.opencost.platforms.openshift.monitoringServiceAccountNamespace | quote }}
roleRef:
  kind: Role
  name: {{ include "opencost.fullname" . }}-reader
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
