{{- if .Values.oidc }}
{{- if .Values.oidc.secretName }}
{{- if .Values.oidc.clientSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.oidc.secretName }}
  labels:
    {{ include "costmodel.commonLabels" . | nindent 4 }}
stringData:
  clientSecret: {{ .Values.oidc.clientSecret }}
{{- end -}}
{{- end -}}
{{- end -}}