{{- if and .Values.opencost.exporter.adminToken.value (not .Values.opencost.exporter.adminToken.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencost.fullname" . }}-admin-token
  namespace: {{ include "opencost.namespace" . }}
  labels: {{- include "opencost.labels" . | nindent 4 }}
  {{- with .Values.secretAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ .Values.opencost.exporter.adminToken.secretKey | default "ADMIN_TOKEN" }}: {{ .Values.opencost.exporter.adminToken.value | toString | b64enc | quote }}
{{- end }}
