appVersion: 1.106.3
version: 0.1.0
description: Prometheus OpenCost Exporter
home: https://github.com/opencost/opencost-helm-chart
name: prometheus-opencost-exporter
sources:
- https://github.com/prometheus-community/opencost_exporter
apiVersion: v2
type: application
keywords:
- opencost
- prometheus
- exporter
maintainers:
- email: mattray@kubecost.com
  name: mattray
