name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    strategy:
      matrix:
        k8s:
          - v1.21.14
          - v1.22.15
          - v1.23.13
          - v1.24.7
          - v1.25.3
          - v1.26.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build ci/test-values.yaml
        uses: mikefarah/yq@v4.30.6
        with:
          cmd: yq eval-all '. as $item ireduce ({}; . * $item)' charts/opencost/values.yaml charts/opencost/ci/.ci.values.yaml &> charts/opencost/ci/test-values.yaml

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

# Skip linter to mitigate false positive comment result
#      - name: Run chart-testing (lint)
#        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          node_image: kindest/node:${{ matrix.k8s }}

      # To run locally with docker
      # docker run -it --network host --workdir=/data --volume ~/.kube/config:/root/.kube/config:ro --volume $(pwd):/data quay.io/helmpack/chart-testing:v3.5.0 ct install --config .github/linters/ct.yaml
      - name: Run chart-testing (install)
        run: ct install --config .github/linters/ct.yaml
